name: multislider
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: Alejandro Corsino <alecorsino@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

# dev_dependencies:
#   test: ^1.0.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.0.0
  flutter_test:
    sdk: flutter
